In [1]:
import numpy
numpy.__version__

'1.18.5'

In [3]:
import numpy as np

NumPy arrays contain values of a single type.

### Arrays
The Numpy array is fixed-type data container.

In [3]:
from IPython.display import display, Image
i = Image(url = 'https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png')
display(i)

In [3]:
# Arrays can be created from lists
np.array([9, 7, 8, 5])

array([9, 7, 8, 5])

In [4]:
# If there are different types in the list, Numpy upcasts
np.array([1, 7.89, 5])

array([1.  , 7.89, 5.  ])

In [5]:
# setting the data type explicitly
np.array([9,7,8,5], dtype='float64')

array([9., 7., 8., 5.])

In [6]:
# one-dimensional array containing only ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
# Two-dimensional array containing only zeros
np.zeros((2, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Fill a two-dimensional array with a specific number
np.full((2, 3), 7.89)

array([[7.89, 7.89, 7.89],
       [7.89, 7.89, 7.89]])

In [9]:
# A sequence starting from 0 to 12 with increment of 3
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [10]:
# Equally spaced values of 6 numbers between 0 and 1
np.linspace(0, 1, 6) # (b-a) / (n-1) = (1-0) / (6-1) = 0.2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [11]:
# Two-dimensional array of random numbers from a uniform distribution on [0,1]
np.random.random((2, 3))  # R runif()

array([[0.37322514, 0.15916974, 0.84114763],
       [0.05664326, 0.78105842, 0.56467042]])

In [12]:
# Two-dimensional array of random numbers from  a normal distribution with mean=0 and standard deviation = 1
np.random.normal(0, 1, (2, 3))

array([[ 0.06471908, -0.45623021,  0.50578749],
       [-0.24896054, -0.5787993 , -0.5531046 ]])

In [13]:
# Two-dimensional array of random integers in the interval [0, 20)
np.random.randint(0, 20, (2, 3))

array([[ 7,  5, 13],
       [ 4, 17,  7]])

In [14]:
# The 4x4 identity matrix 
np.eye(4)  # eye means I, i.e, Identity. Matrix A multiplied by I -> np.matmul(A,I) = A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Array attributes

In [16]:
 # Reproducibility
np.random.seed(0) 
a1 = np.random.randint(10, size=5) 
a1

array([5, 0, 3, 3, 7])

In [5]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 5)
a2

array([5, 0, 3, 3, 7])

In [18]:
# A three-dimensional array ----> Tensor
a3 = np.random.randint(10, size=(3, 2, 5))
a3


array([[[9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]],

       [[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4]],

       [[3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]]])

In [19]:
i = Image(url = 'https://www.tensorflow.org/guide/images/tensor/3-axis_front.png')
display(i)

In [20]:
# The attributes of the 3-dim array a3
print("a3 ndim: ", a3.ndim)
print("a3 shape:", a3.shape)
print("a3 size: ", a3.size)

a3 ndim:  3
a3 shape: (3, 2, 5)
a3 size:  30


In [21]:
# The dat type of the content
a3.dtype

dtype('int64')

In [22]:
# The bytes of each item(element) and the total bytes of the array
print("itemsize:", a3.itemsize, "bytes")
print("totalbytes:", a3.nbytes, "bytes")

itemsize: 8 bytes
totalbytes: 240 bytes


### Indices of arrays

In [23]:
# Similar to indices of lists. counting starts from zero
a1



array([5, 0, 3, 3, 7])

In [24]:
a1[0]

5

In [25]:
a1[4]

7

In [26]:
a1[-1]

7

In [27]:
# Indices of a two-dimensional array
a2 = np.random.randint(10, size=(2, 3))  
a2

array([[3, 3, 7],
       [0, 1, 9]])

In [28]:
a2[0,0]

3

In [29]:
a2[1,2]

9

In [30]:
a2[-1,-1]

9

In [31]:
# Assign values. Note that a different type will be converted since arrays are fixed-type
a2[1,2] = 100.89
a2

array([[  3,   3,   7],
       [  0,   1, 100]])

### Slicing arrays

In [32]:
# slice of a is a[start:stop:step]
#default start=0, stop=size of dimension, step=1.

a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
a[:2]

array([0, 1])

In [34]:
a[2:]

array([2, 3, 4, 5, 6, 7])

In [35]:
a[1:4]

array([1, 2, 3])

In [36]:
a[::3] # takes step size of 3

array([0, 3, 6])

In [37]:
a[2::3] # takes step size of 3 starting at 2

array([2, 5])

In [38]:
# negative step value means exchanging start and stop
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
a[6::-2]

array([6, 4, 2, 0])

In [40]:
# 2-dim array
b = np.random.randint(0, 10, (4, 5))
b

array([[9, 0, 4, 7, 3],
       [2, 7, 2, 0, 0],
       [4, 5, 5, 6, 8],
       [4, 1, 4, 9, 8]])

In [41]:
# First two rows and first 3 columns
c = b[:2, :3] 
c

array([[9, 0, 4],
       [2, 7, 2]])

In [42]:
# If you change an element of subarray c , then the array b changes too. c is not copy of b
c[1,2] = 555
print(c)


[[  9   0   4]
 [  2   7 555]]


In [43]:
# Check if b changed too
b 

array([[  9,   0,   4,   7,   3],
       [  2,   7, 555,   0,   0],
       [  4,   5,   5,   6,   8],
       [  4,   1,   4,   9,   8]])

In [44]:
# To get a copy of b
c_copy = b[:2, :3].copy()
c_copy[0,0] = 777
c_copy

array([[777,   0,   4],
       [  2,   7, 555]])

In [45]:
# But b did not change
b

array([[  9,   0,   4,   7,   3],
       [  2,   7, 555,   0,   0],
       [  4,   5,   5,   6,   8],
       [  4,   1,   4,   9,   8]])

In [46]:
# only first column
b[:,0]

array([9, 2, 4, 4])

In [47]:
# only first row
b[0,:]

array([9, 0, 4, 7, 3])

In [48]:
# Equivalently
b[0]

array([9, 0, 4, 7, 3])

In [49]:
# 3-dim array --> Tensor
a3

array([[[9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]],

       [[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4]],

       [[3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]]])

In [50]:
a3[0]

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [51]:
a3[1,1,1]

9

In [52]:
a3[:,1,:]

array([[7, 6, 8, 8, 1],
       [5, 9, 8, 9, 4],
       [2, 3, 8, 1, 3]])

In [53]:
### Reshape

In [54]:
# Recall the array a
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [55]:
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
a.reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [57]:
a.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

### Concatenate

In [58]:
np.concatenate([a, a])

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
np.concatenate([a2, a2]) # default axis = 0 , i.e., rows

array([[  3,   3,   7],
       [  0,   1, 100],
       [  3,   3,   7],
       [  0,   1, 100]])

In [60]:
np.concatenate([a2, a2], axis = 1)

array([[  3,   3,   7,   3,   3,   7],
       [  0,   1, 100,   0,   1, 100]])

### Universal functions


In [61]:
# A vectorized operation is done on each element of an array
print("a + 1 =", a + 1)
print("a ** 2 = ", a ** 2)

a + 1 = [1 2 3 4 5 6 7 8]
a ** 2 =  [ 0  1  4  9 16 25 36 49]


In [62]:
np.add(a,1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
-a

array([ 0, -1, -2, -3, -4, -5, -6, -7])

In [64]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ])

In [65]:
np.exp(a) # np.exp2(a) or np.power(7,a), i.e., 7**a

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [66]:
np.log(a) # np.log2(a) or np.log10(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [67]:
# Sum of elements
np.sum(a) # you can use array methods a.sum()


28

In [68]:
print(np.max(a))
np.min(a)

7


0

In [69]:
# mean and standard deviation
print(a.mean())
a.std()

3.5


2.29128784747792

In [70]:
# Recall a2
a2

array([[  3,   3,   7],
       [  0,   1, 100]])

In [71]:
# sum of all the elements
a2.sum() # or np.sum(a2)  


114

In [72]:
a2.sum(axis = 0)  # collapsing rows

array([  3,   4, 107])

In [73]:
a2.sum(axis = 1)  # collapsing columns

array([ 13, 101])

### Broadcasting

In [74]:
# We had already a + 1. Since the scalar 1 is zero-dim, it is broadcasted to [1,1,1,1,1,1,1,1]
# Now for higher-dim, let us introduce x and add to a2
x = np.full(3, 8)
x


array([8, 8, 8])

In [75]:
a2 

array([[  3,   3,   7],
       [  0,   1, 100]])

In [76]:
a2 + x

array([[ 11,  11,  15],
       [  8,   9, 108]])

In [77]:
y = np.full(2, 8).reshape(2,1)
y

array([[8],
       [8]])

In [78]:
a2 + y

array([[ 11,  11,  15],
       [  8,   9, 108]])

### Mean-centering of 2D array


In [79]:
z = np.random.random((5, 2))
z_mean = z.mean(axis=0) # collapsing rows axis = 0 to calculate the column means
print(z)
z_mean

[[0.90234858 0.09928035]
 [0.96980907 0.65314004]
 [0.17090959 0.35815217]
 [0.75068614 0.60783067]
 [0.32504723 0.03842543]]


array([0.62376012, 0.35136573])

In [80]:
z_mean_centered = z - z_mean
z_mean_centered.mean(axis=0) # close to zero


array([-4.44089210e-17,  2.22044605e-17])

### Boolean Comparisons and Masks

In [81]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False])

In [82]:
a >= 6

array([False, False, False, False, False, False,  True,  True])

In [83]:
(a < 7) & (a > 4)

array([False, False, False, False, False,  True,  True, False])

In [84]:
a2 == 100

array([[False, False, False],
       [False, False,  True]])

In [85]:
# Count number of elements less than 5
np.count_nonzero(a < 5)

5

In [86]:
# Equivalent
np.sum( a < 5) # since False = 0 and True = 1

5

In [87]:
a2

array([[  3,   3,   7],
       [  0,   1, 100]])

In [88]:
np.sum(a2) # sum over all elements in the matrix

114

In [89]:
np.sum(a2 < 5) # how many elements less than 5 in the matrix

4

In [90]:
np.sum(a2 < 5, axis=1) # collapse columns, i.e., how many elements less than 5 in each row

array([2, 2])

In [91]:
np.any(a > 7)

False

In [92]:
np.all(a < 8)

True

In [93]:
# Masks
a[a < 5] # means a[True, True, True, True, True, False, False, False]

array([0, 1, 2, 3, 4])

### Sorting

In [94]:
unsorted = np.array([7,1,6,4,5])
unsorted

array([7, 1, 6, 4, 5])

In [95]:
arr_new = np.sort(unsorted)
print(arr_new)
unsorted

[1 4 5 6 7]


array([7, 1, 6, 4, 5])

In [96]:
unsorted.sort() # It sorts the array in-place
unsorted

array([1, 4, 5, 6, 7])

In [97]:
# The indices of the sorted elements
unsorted_2 = np.array([7,1,6,4,5])
indices = unsorted_2.argsort()
indices

array([1, 3, 4, 2, 0])

In [98]:
unsorted_2[indices]

array([1, 4, 5, 6, 7])

In [99]:
a2

array([[  3,   3,   7],
       [  0,   1, 100]])

In [100]:
np.sort(a2, axis =0) # collapse rows,i.e., sort each column

array([[  0,   1,   7],
       [  3,   3, 100]])

In [101]:
np.sort(a2, axis =1) # collapse columns,i.e., sort each row

array([[  3,   3,   7],
       [  0,   1, 100]])